name: road_map_project
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-150.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_svg: ^1.0.3
  shared_preferences: ^2.0.13
  flutter_screenutil: ^5.5.2
  smooth_page_indicator: ^1.0.0+2
  firebase_core: ^1.16.0
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  dio: ^4.0.6
  font_awesome_flutter: ^10.1.0

#  flutter_launcher_icons: "^0.9.2"
  flutter_native_splash: ^2.1.6

#flutter_icons:
#  android: true
#  ios: true
#  color: "#195860"
#  image_path: "assets/icons/launcher_icon.png"
#  remove_alpha_ios: true

flutter_native_splash:
  image: assets/images/splash.png
  color: "#195860"
  icon_background_color: "#195860"
  android: true
  ios: true
  android_gravity: fill
  fullscreen: true

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Nunito
      fonts:
        - asset: font/EXTRABOLD.ttf
          weight: 800
        - asset: font/BOLD.ttf
          weight: 700
        - asset: font/SEMIBOLD.ttf
          weight: 600
        - asset: font/REGULAR.ttf
          weight: 400
        - asset: font/LIGHT.ttf
          weight: 300